[package]
name = "lompsa_rust"
version = "0.1.0"
authors = ["Samuli Lehtonen <cr0xxy94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version="1.4.5", features = ["sqlite"] }
